name: Deploy Docker Compose Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Connexion au Docker Host (si nécessaire, par exemple via Docker Swarm)
      # Vous pouvez configurer un service ou héberger sur GitHub-hosted runners.

      # Étape 3 : Passer le secret au docker-compose
      - name: Deploy Docker Compose Stack
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > .env
          docker-compose up --build -d
